fix(disa/ida) use BasicBlock.endEA instead of .end_ea
I encountered a crash running karta_matcher on ida6.9 (linux) with the error: `'BasicBlock' object has no attribute 'end_ea'`.

Testing locally I found that a BasicBlock only have `endEA` and `startEA`, also example online use these variables.